#!/bin/bash
echo -e "\e[1;33mEnter your Name\e[0m"
read name
if [ $1 == "grade" ]
then
case $2 in

        task1)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task1 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
var1=$( cat /root/myfile.doc 2> /dev/null)
check=0
if [ -f /root/myfile.doc ] 2> /dev/null
then
        echo -e "\e[1;32mfile /root/myfile.doc is present\e[0m"
        if [[ $var1 == "/root" ]] 2> /dev/null
        then
                echo -e "\e[1;32mfile content match\e[0m"
                check=$((check+1))
        else
                echo -e "\e[1;31mfile content did not match\e[0m"
        fi
else

        echo -e "\e[1;31mfile /root/myfile.doc is not present\e[0m"
fi
if [ $check -eq 1 ]
then
 echo -e "\e[1;32m-----Task is Sucessful-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Sucessful-----\e[0m"
fi

        ;;
        task2)
#!bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task2 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
check=0
for var in {1..3}
do
        if [ -f  /root/file$var ] 2> /dev/null
        then
                check=$((check+1))
                echo -e "\e[1;32mfile /root/file$var is present\e[0m"
        else
                echo -e "\e[1;31mfile /root/file$var is not present\e[0m"
        fi
done
if [ $check -eq 3 ] 2> /dev/null
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
        task3)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task3 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
var1=$(date | cut -d " " -f 1,2,3) 2> /dev/null
var2=$(cat /date.txt 2> /dev/null | cut -d " " -f 1,2,3)
check=0
if [ -f /date.txt ]
then
        echo -e "\e[1;32mfile /date.txt is present\e[0m"
        if [[ $var1 == $var2 ]]
        then
                echo -e "\e[1;32mfile content match\e[0m"
                check=$((check+1))
        else
                echo -e "\e[1;31mfile content did not match\e[0m"
        fi
else
        echo -e "\e[1;31mfile /date.txt is not present\e[0m"
fi
if [[  check -eq 1 ]]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi

        ;;
        task4)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task4 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
var1=$(ls /bin 2> /dev/null)
var2=$(cat /list.txt 2> /dev/null)
check=0
if [ -f /list.txt ]
then
        echo -e "\e[1;32mfile /list.txt is present\e[0m"
        if [[ $var1 == $var2 ]]
        then
                echo -e "\e[1;32mfile content match\e[0m"
                check=$((check+1))
        else
                echo -e "\e[1;31mfile content did not match\e[0m"
        fi
else
        echo -e "\e[1;31mfile /list.txt is not present\e[0m"
fi
if [[  check -eq 1 ]]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
        task5)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task5 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
var1=$(whoami && pwd 2> /dev/null)
var2=$(pwd && whoami 2> /dev/null)
var3=$(cat /root/mydata/userfile.txt 2> /dev/null)
check=0
if [ -d /root/mydata ]
then
        echo -e "\e[1;32mDirectory /root/mydata is present\e[0m"
	if [[ -f /root/mydata/userfile.txt ]]
        then
		echo -e "\e[1;32mfile /root/mydata/userfile.txt is present\e[0m"
		if [[ $var1 == $var3 ]]
                then
			check=$((check+1))
			echo -e "\e[1;32mfile content match\e[0m"
		elif [[ $var2 == $var3 ]]
		then
			echo -e "\e[1;32mfile content match\e[0m"
               		check=$((check+1))
        	else
                	echo -e "\e[1;31mfile content did not match\e[0m"
		fi
	else 
		echo -e "\e[1;31mfile /root/mydata/userfile.txt is not present\e[0m"
        fi
else
        echo -e "\e[1;31mdirectory /root/mydata is not present\e[0m"
fi
if [[  check -eq 1 ]]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi

        ;;
        task6)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task6 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
check=0
if [ -d /root/unnati ]
then
        echo -e "\e[1;32mdirectory /root/unnati is present\e[0m"
	if [[ -d /root/unnati/cidco ]]
        then
		echo -e "\e[1;32mdirectory /root/unnati/cidco is present\e[0m"
		if [[ -d /root/unnati/cidco/aurangabad ]]		
		then
			echo -e "\e[1;32mdirectory /root/unnati/cidco/aurangabad is present\e[0m"
               		check=$((check+1))
        	else
                	echo -e "\e[1;31mdirectory /root/unnati/cidco/aurangabad is not present\e[0m"
		fi
	else 
		echo -e "\e[1;31mdirectory /root/unnati/cidco is not present\e[0m"
        fi
else
        echo -e "\e[1;31mdirectory /root/unnati is not present\e[0m"
fi
if [[  check -eq 1 ]]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
        task7)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task7 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
check=0
for var in {1..10}
do
	if [ -d  /root/linuxdata$var ]
	then
		check=$((check+1))
		echo -e "\e[1;32mDirectory /root/linuxdata$var present\e[0m"
	else
		echo -e "\e[1;31mDirectory /root/linuxdata$var is not present\e[0m"
	fi
done
if [ $check -eq 10 ]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
        task8)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task8 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
check=0
if [ -d /root/data/gdata/reddata/ ]
then
        echo -e "\e[1;32mDirectory /root/data/gdata/reddata is present\e[0m"

for var in {1..10}
do
        if [ -f  /root/data/gdata/reddata/unnati$var.php ]
        then
                check=$((check+1))
                echo -e "\e[1;32mfile /root/data/gdata/reddata/unnati$var.php present\e[0m"
        else
                echo -e "\e[1;31mfile /root/data/gdata/reddata/unnati$var.php is not present\e[0m"
        fi
done
else
        echo -e "\e[1;31mDirectory /root/data/gdata/reddata is not present\e[0m"
fi
if [ $check -eq 10 ]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
        task9)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task9 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
var1=$(cat /etc/fstab 2> /dev/null)
var2=$(cat /root/mdata/fstab.backup 2> /dev/null)
check=0
if [ -d /root/mdata ]
then
        echo -e "\e[1;32mdirectory /root/mdata is present\e[0m"
	if [[ -f /root/mdata/fstab.backup ]]
        then
                echo -e "\e[1;32mfile /root/mdata/fstab.backup is present\e[0m"
		if [[ $var1 == $var2 ]]
		then 
			echo -e "\e[1;32mfile content is match\e[0m"
               		check=$((check+1))
        else
                echo -e "\e[1;31mfile content did not match\e[0m"
        fi
else
	echo -e "\e[1;31mfile /root/mdata/fstab.backup is not present\e[0m"
	fi
else
        echo -e "\e[1;31mdirectory /root/mdata is not present\e[0m"
fi
if [[  check -eq 1 ]]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
        task10)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task10 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
check=0
for var in {1..5}
do
        if [ -f  /tmp/appfile$var.xml ]
        then
                echo -e "\e[1;32mfile /appfile$var.xml is moved\e[0m"
		check=$((check+1))
	else
		echo -e "\e[1;31mfile /appfile$var.xml is not moved\e[0m"
	fi
done
for var in {1..5}
do
	if [ -f /tmp/kdata/appfile$var.html ]
	then
		echo -e "\e[1;32mfile /tmp/kdata/appfile$var.html is moved\e[0m"
              	check=$((check+1))
        else
               	echo -e "\e[1;31mfile /tmp/kdata/appfile$var.html is not moved\e[0m"
        fi
done
if [ $check -eq 10 ]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
        task11)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task11 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
var1=$(cat /etc/fstab 2> /dev/null)
var2=$(cat /tmp/fstab.backup 2> /dev/null)
check=0
if [ -f /tmp/fstab.backup ]
then
        echo -e "\e[1;32mfile /tmp/fstab.backup is present\e[0m"
	if [[ $var1 == $var2 ]]
	then 
	echo -e "\e[1;32mfile /tmp/fstab.abckup content's relocated successfully\e[0m"
               check=$((check+1))
        else
                echo -e "\e[1;31mfile content did not match\e[0m"
        fi
else
	echo -e "\e[1;31mfile /tmp/fstab.backup is not present\e[0m"
fi
if [[  check -eq 1 ]]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi

        ;;
        task12)
#!/bin/bash
echo -e "\e[1;34m===================================================================\e[0m"
echo -e "\e[1;32m Exclusive task for Unnati Student\e[0m \e[1;31m http://unnatidevelopment.in/ \e[0m"
echo -e "\e[1;33m                 Grading RHCSA+CLA-MODULE_1 Task12 \e[0m"
echo -e "\e[1;34m===================================================================\e[0m"
#!/bin/bash
check=0
for var in {1..10}
do
        if [ -f  /root/.unnati$var.xls ]
        then
                check=$((check+1))
                echo -e "\e[1;32mfile /root/.unnati$var.xls is present\e[0m"

        else
                echo -e "\e[1;31mfile /root/.unnati$var.xls is not present\e[0m"
        fi
done
if [ $check -eq 10 ]
then
echo -e "\e[1;32m-----Task is Successfull-----\e[0m"
else
 echo -e "\e[1;31m-----Task is not Successfull-----\e[0m"
fi
        ;;
	*)
 echo -e "\e[1;31m-----$2 not present-----\e[0m"
esac

fi
